#!/bin/sh
#/etc/init.d/telegram_auto

### BEGIN INIT INFO
# Provides:		telegram
# Required-Start:	$all
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	simple script para lanzar el tema
# Description:		script que lanza el tema
### END INIT INFO
case "$1" in
	start)
	  echo "Lanzando telegram"
		#se arranca la aplicacion
	  /home/pi/tg/telegram -k /home/pi/tg/tg-server.pub -s /home/pi/tg/prueba.lua
	  ;;
	stop)
	  echo "Parando telegram"
		#nos cargamos la aplicacion
	  killall telegram
	  ;;
	*)
	  echo "Usage: /etc/init.d/telegram_auto {start|stop}"
	  exit 1
	  ;;
esac

exit 0

